- hosts: localhost
  vars:
   resource_group: RG2
   vmss_name: "{{resource_group}}VMSS01"
   vmss_lb_name: "{{ vmss_name }}lb"
   location: southeastasia
   admin_username: tadmin
  #admin_password: "your_password"
   #to be updated with Vault azure/ansible file
   admin_password: "Build@2000"
  roles:
   - resourcegroup
   - vNet
   - loadbalancer
   - vmss
